sport_ids:
  handball:
    leagues:
      - name: "EHF Euro Cup"
        country: "Europe"
        url: "https://www.flashscore.com/handball/europe/ehf-euro-cup"
        seasons: [2025]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"
      - name: "European Championship"
        country: "Europe"
        url: "https://www.flashscore.com/handball/europe/european-championship"
        seasons: [2026, 2024]
        url_pattern: "{base_url}-{season}/results/"
      - name: "Herre Handbold Ligaen"
        country: "Denmark"
        url: "https://www.flashscore.com/handball/denmark/herre-handbold-ligaen"
        seasons: [2025, 2024]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"
      - name: "Kvindeligaen Women"
        country: "Denmark"
        url: "https://www.flashscore.com/handball/denmark/kvindeligaen-women"
        seasons: [2025, 2024]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"
      - name: "Starligue"
        country: "France"
        url: "https://www.flashscore.com/handball/france/starligue"
        seasons: [2025, 2024]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"
      - name: "Liga ASOBAL"
        country: "Spain"
        url: "https://www.flashscore.com/handball/spain/liga-asobal"
        seasons: [2025, 2024]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"
      - name: "Handbollsligan Women"
        country: "Sweden"
        url: "https://www.flashscore.com/handball/sweden/handbollsligan-women"
        seasons: [2025, 2024]
        url_pattern: "{base_url}-{previous_season}-{season}/results/"

  # volleyball:
  #   leagues:
  #     - name: "PlusLiga"
  #       country: "Poland"
  #       url: "https://www.flashscore.com/volleyball/poland/plusliga"
  #       seasons: [2025, 2024]
  # football:
  #   leagues:
  #     - name: "LaLiga"
  #       country: "Spain"
  #       url: "https://www.flashscore.com/football/spain/laliga"
  #       seasons: [2025]
